name: Test Mgcb
on:
  workflow_dispatch:
    inputs:
      checkoutRef:
        type: string
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Allow all matrix jobs to continue even if one fails
      matrix:
        # macos-14 is an M1 machine
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        platform: [Android, DesktopGL, Windows, MacOSX, iOS]
        profile: [Reach, HiDef]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{matrix.os}}
      cancel-in-progress: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{inputs.checkoutRef}}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build (unix)
        if: matrix.os != 'windows-latest'
        run: ./build.sh

      - name: Build (win)
        if: matrix.os == 'windows-latest'
        run: ./build.ps1

      - name: Run MGCB
        working-directory: ./testProject
        run: MG_PLATFORM=${{matrix.platform}} MG_PROFILE=${{matrix.profile}} ../Artifacts/MonoGame.Content.Builder/Release/mgcb --@=./content.mgcb
     
      - name: Upload TestProject Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testProject-${{ matrix.os }}
          path: ./testProject